title: Xuefeng Xu's Homepage | CivilTechLabs
page-top-title: CivilTechLabs
top-section-bg-text: CivilTechLabs
home-subtitle: Xuefeng Xu&ensp;|&ensp;许雪峰
copyright-text: '&copy; Xuefeng Xu 2021-2026. All Rights Reserved.'
