title: Xuefeng Xu's Homepage
page-top-title: Xuefeng Xu
top-section-bg-text: CivilTechlabs
home-subtitle: Xuefeng Xu&ensp;|&ensp;许雪峰
copyright-text: '&copy; Xuefeng Xu 2021-2026. All Rights Reserved.'
